config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :edit, :update]
  get 'serch/index'
  get 'selects/index'
  root 'pages#help'
  resources :notes do
    resources :notecomments
  end
  resources :pages do
    resources :tweets
  end
  resources :tweets do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :users do
  member do
   get :following, :followers
  end
  end
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  get 'goods/index'
  post '/goods', to: 'goods#create'
  get 'mores/index'
  post '/mores', to: 'mores#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/more.rb
class More < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :notecomments
  has_many :mores
  has_many :more_users, through: :mores, source: 'user'
  belongs_to :user
end

app/models/notecomment.rb
class Notecomment < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :following, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :goods
  has_many :good_users, through: :goods, source: 'user'
  has_many :comments
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :notecomments

  has_many :mores
  has_many :more_notes, through: :mores, source: 'note'
  has_many :goods
  has_many :good_tweets, through: :goods, source: 'tweet'
  has_many :tweets
  has_many :notes
  # フォロー機能関係のコード
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_secure_password

  mount_uploader :image, ImageUploader

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    if following.ids.include?(other_user.id)
      return true
    end
      return false
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def new
    @note = Note.new
  end
  def create
    @note = Note.new(note_params)
    @note.user = current_user
    if @note.save
      redirect_to :action => "index"
    end
  end
  def show
    @note = Note.find(params[:id])
  end
  def index
    @notes = Note.all
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
  @note = Note.find(params[:id])

  if @note.update(note_params)
    redirect_to @note
  else
    render 'edit'
  end
  end

  def destroy
  @note = Note.find(params[:id])
  @note.destroy

  redirect_to notes_path
  end

  private def note_params
    params.require(:note).permit(:genre,:title,:contents)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(tweet)
    tweet.user_id == current_user.id
  end

  def user_confirmation(objects)
    tweet_id = objects.user_id
    if tweet_id == current_user.id
      return true
    else
      return false
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/mores_helper.rb
module MoresHelper
end

app/helpers/notecomments_helper.rb
module NotecommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/serch_helper.rb
module SerchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notes/edit.html.erb
<div class="container">
<div class="box-all">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 col-group">
      <h1 class="text-center acount">This is the page for making notes</h1>
    </div>
  </div>
  <div class="box-all-1">
  <%= form_for @note, url: note_path(@note), method: :patch, :html => {:class => "form-group"} do |f| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-group">
        <h4 class="text-center"><%= f.label :genre%></h4>
        <h4 class="text-center"><%= f.text_field :genre, class:"field" %></h4>
        <h4 class="text-center"><%= f.label :title %></h4>
        <h4 class="text-center"><%= f.text_field :title, class:"field" %></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-group">
      <h4 class="text-center"><%= f.label :contents %></h4>
      <h4 class="text-center"><%= f.text_area :contents, class:"field"%></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-group">
      <div class="submit-btn"><%= f.submit "make",class:'btn btn-primary btn-lg center-block btn-circl btn-xl' %></div>
    </div>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/notes/index.html.erb
<div class="features-boxed">
    <div class="container">
        <div class="intro">
            <h1 class="text-center title">・Notebook・</h1>
            <h2 class="text-center">Here is a page that allows you to view notes written by everyone.</h2>
            <div class="row">
            <div class="col-md-4 col-md-offset-4">
            <a href="/notes/new">
            <button type="button" class="btn btn-info btn-lg center-block">make note </button>
            </a>
            </div>
            </div>
        </div>
        <div class="row justify-content-center features">
        <%@notes.each do |note|%>
            <div class="col-md-4 item">
                <div class="box">
                    <div class="user-information"><%= image_tag note.user.image.url, class: 'rounded-circle'%>　<%= note.user.username %></div>
                    <h3 class="name"><%=note.title%></h3>
                    <h3 class="description1"><%=note.genre%></h3>
                    <h4 class="description2"><%=note.contents%></h4>
                    <a href="#" class="learn-more">Learn more »</a>
                    <%= link_to 'Comment', note_path(note) %>
                    <%if (user_confirmation(note)) %>
                    <%= link_to 'Edit', edit_note_path(note) %>
                    <%= link_to 'Destroy', note_path(note),method: :delete, data: { confirm: 'Are you sure?' } %>
                    <%end%>
                    <% if !note.more_users.include?(current_user) %>
                    <%= link_to mores_path(note_id: note.id), method: :post do %>
                    <%= image_tag 'icons/more.png', class: 'topic-index-icon' %>
                    <% end %>
                    <% end %>
                </div>
            </div>
        <%end%>
        </div>
    </div>
</div>

app/views/notes/new.html.erb
<div class="notes-new-page">
  <div class="container">
    <div class="box-all"> 
      <div class="row">
        <div class="col-md-8 col-md-offset-2 col-group">
          <h1 class="text-center acount">This is the page for making notes</h1>
        </div>
      </div>
    <div class="box-all-1">
      <%= form_for @note, url:notes_path, :html => {:class => "form-group"} do |f| %>
        <div class="row">
          <div class="col-md-4 col-md-offset-4 col-group">
            <h4 class="text-center"><%= f.label :genre%></h4>
            <h4 class="text-center"><%= f.text_field :genre, class:"field" %></h4>
            <h4 class="text-center"><%= f.label :title %></h4>
            <h4 class="text-center"><%= f.text_field :title, class:"field" %></h4>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-4 col-group">
            <h4 class="text-center"><%= f.label :contents %></h4>
            <h4 class="text-center"><%= f.text_area :contents, class:"field"%></h4>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-4 col-group">
          <div class="submit-btn"><%= f.submit "make",class:'btn btn-primary btn-lg center-block btn-circl btn-xl' %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="container">
  <div class="intro">
      <h1 class="text-center title">・Notebook・</h1>
      <h2 class="text-center subtitle">This page is a page where you can check the details of each note or a comment.</h2>
  </div>
  <div class="row row-show">
    <div class="col-md-1 text-space">
    </div>
    <div class="col-md-4 text-center">
      <p>
        <h3 class="strong">・Genre・</h3><br>
        <h4 class="instance"><%= @note.genre%></h4>
      </p>
      <p>
        <h3 class="strong">・Title・</h3><br>
        <h4 class="instance"><%= @note.title%></h4>
      </p>
      <p>
        <h3 class="strong">・contents・</h3><br>
        <p class="instance"><%= @note.contents%></p>
      </p>
    </div>
    <div class="col-md-1 text-space">
    </div>
    <div class="col-md-6 text-center">
      <h2 class="strong">Comments</h2>
      <% @note.notecomments.each do |notebook| %>
        <p>
          <div class="strong">Comment area:</div>
          <div class="instance"><%=notebook.user.username %>　<%= notebook.body %></div>
        </p>
      <% end %>
      <h2 class="strong">Create comment:</h2>
        <%= form_for([@note, @note.notecomments.build]) do |f| %>
          <p>
            <%= f.text_area :body %>
          </p>
          <p>
            <%= f.submit "create",class: 'btn btn-primary btn-lg btn-circle1 btn-xl center-block tweet-text' %>
          </p>
        <% end %>
    </div>
  </div>
</div>