config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :edit, :update]
  get 'serch/index'
  get 'selects/index'
  root 'pages#help'
  resources :notes do
    resources :notecomments
  end
  resources :pages do
    resources :tweets
  end
  resources :tweets do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :users do
  member do
   get :following, :followers
  end
  end
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  get 'goods/index'
  post '/goods', to: 'goods#create'
  get 'mores/index'
  post '/mores', to: 'mores#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/more.rb
class More < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :notecomments
  has_many :mores
  has_many :more_users, through: :mores, source: 'user'
  belongs_to :user
end

app/models/notecomment.rb
class Notecomment < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :following, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :goods
  has_many :good_users, through: :goods, source: 'user'
  has_many :comments
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :notecomments

  has_many :mores
  has_many :more_notes, through: :mores, source: 'note'
  has_many :goods
  has_many :good_tweets, through: :goods, source: 'tweet'
  has_many :tweets
  has_many :notes
  # フォロー機能関係のコード
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_secure_password

  mount_uploader :image, ImageUploader

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    if following.ids.include?(other_user.id)
      return true
    end
      return false
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def new
    @tweet=Tweet.new
  end

  def create
    @tweet=Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      redirect_to @tweet
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def index
    @tweet = Tweet.all
    @user = User.all
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
    redirect_to @tweet
    else
    render 'edit'
    end
  end

  def destroy
  @tweet = Tweet.find(params[:id])
  @tweet.destroy

  redirect_to tweet_path
  end

  private def tweet_params
    params.require(:tweet).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(tweet)
    tweet.user_id == current_user.id
  end

  def user_confirmation(objects)
    tweet_id = objects.user_id
    if tweet_id == current_user.id
      return true
    else
      return false
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/mores_helper.rb
module MoresHelper
end

app/helpers/notecomments_helper.rb
module NotecommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/serch_helper.rb
module SerchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :following_id, @tweet.ids %></div>
  <%= f.submit "Follow", class: "btn btn-primary center-block" %>
<% end %>

app/views/tweets/_follow_form.html.erb
  <div id="follow_form">
  <% if current_user.following?(tweet_user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>

app/views/tweets/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(following_id: @user),html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-danger center-block unfollow-button" %>
<% end %>

app/views/tweets/edit.html.erb
<div class="highlight-blue">
    <div class="container">
      <%= form_for @tweet, url: tweet_path(@tweet), method: :patch do |f| %>
        <div class="intro">
            <h1 class="text-center tweetpage">This is tweet page</h1>
            <h3 class="text-center tweetpage">Please enter the content you want to tweet in the bottom form.</h3>

            <p class="text-center">
              <%= f.label :text, class: "text-center" %><br>
              <%= f.text_area :text, class: "text-center"%>
            </p>


        </div>
        <div class="buttons"><%= f.submit "tweet",class: 'btn btn-primary btn-lg btn-circle1 btn-xl center-block tweet-text'%></div>
        <%end%>
    </div>
</div>

app/views/tweets/index.html.erb
<div class="testimonials-clean">
    <div class="container">
        <div class="intro">
            <h1 class="text-center title">All of tweets</h1>
            <h2 class="text-center subtitle">This is the page where you can see the contents of all tweets.</h2>
            <a href="/tweets/new">
            <button type="button" class="btn btn-info btn-lg center-block"> Let's tweet  </button>
            </a>
        </div>
        <div class="row people">
          <% @tweet.each do |tweet| %>
            <div class="col-md-6 col-lg-4 item">
                  <div class="author text-center"><%= image_tag tweet.user.image.url, class: 'rounded-circle', :size =>'180x180' %><h3 class="name text-center"><%= tweet.user.username%></h3></div>
                  <% unless current_user?(tweet) %>
                    <% if logged_in? %>
                      <div id="follow_form">
                        <% if current_user.following?(tweet.user) %>
                          <%= form_for(current_user.active_relationships.find_by(following_id: tweet.user.id),html: { method: :delete }) do |f| %>
                            <%= f.submit "Unfollow", class: "btn btn-danger center-block unfollow-button" %>
                          <% end %>
                        <% else %>
                          <%= form_for(current_user.active_relationships.build) do |f| %>
                            <div><%= hidden_field_tag :following_id, @tweet.ids %></div>
                            <%= f.submit "Follow", class: "btn btn-primary center-block" %>
                          <% end %>
                        <% end %>
                      </div>
                    <% end %>
                  <% end %>
                <div class="box">
                    <p class="description text-center"><%= tweet.text %></p>
                </div>
                <div class="text-center">
                <tr>
                  <%if(user_confirmation(tweet))%>
                  <td><%= link_to 'Edit', edit_tweet_path(tweet)%></td>
                  <td><%= link_to 'Destroy', tweet_path(tweet),method: :delete, data: { confirm: 'Are you sure?' }%></td>
                  <%end%>
                  <td><%= link_to 'Comment', tweet_path(tweet),method: :get%></td>
                  <td><% if !tweet.good_users.include?(current_user) %>
                        <%= link_to goods_path(tweet_id: tweet.id), method: :post do %>
                        <%= image_tag 'icons/good_face.png', class: 'topic-index-icon' %>
                        <% end %>
                      <% end %></td>
                </tr>
              </div>
            </div>
          <% end %>
        </div>
    </div>
</div>

app/views/tweets/new.html.erb
<div class="highlight-blue">
    <div class="container">
      <%= form_for @tweet,url: tweets_path do |f| %>
        <div class="intro">
            <h1 class="text-center tweetpage">This is tweet page</h1>
            <h3 class="text-center tweetpage">Please enter the content you want to tweet in the bottom form.</h3>

            <p class="text-center">
              <%= f.label :text, class: "text-center" %><br>
              <%= f.text_area :text, class: "text-center"%>
            </p>


        </div>
        <div class="submit-buttons"><%= f.submit "tweet",class: 'btn btn-primary btn-lg btn-circle1 btn-xl center-block tweet-text'%></div>
        <%end%>
    </div>
</div>

app/views/tweets/show.html.erb
<div class="highlight-blue">
    <div class="container">
        <div class="intro">
            <h1 class="text-center tweetpage">This is the confirmation page of your tweet content</h1>
            <h3 class="text-center tweetpage">&#x1f447;Your tweet content should be displayed below.&#x1f447;</h3>
        <div class="row">
          <div class="col-md-4 col-md-offset-4 display-box">
            <h3 class="text-center">
              <h3 class="text-center">your tweet:<%= @tweet.text %></h3>
            </h3>
          </div>
          <div class="col-md-4 col-md-offset-4 display-box">
            <h3 class="text-center">
              <h4 class="text-center">Comment field</h4>
                <% @tweet.comments.each do |comment| %>
                  <p class="text-center">
                    <strong class="text-center">Comment:</strong>
                      <%= comment.comment %>
                  </p>
                <% end %>
            </h3>
          </div>
          <div class="col-md-4 col-md-offset-4 display-box">
            <h3 class="text-center">
              <h4 class="text-center">Do you want to comment?</h4>
              <%= form_for([@tweet, @tweet.comments.build]) do |f| %>
              <p class="text-center">
                <%= f.label :comment, class:"text-center" %><br>
                <%= f.text_area :comment, class:"text-center" %>
              </p>
              <p class="text-center">
                <%= f.submit %>
              </p>
              <% end %>
            </h3>
          </div>
        </div>
        <a class="btn btn-primary btn-lg btn-circle1 btn-xl center-block" role="button" href="/tweets#index"><i class="glyphicon glyphicon-list"></i></a>
        </div>
        <div class="buttons"></div>
    </div>
</div>