config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :edit, :update]
  get 'serch/index'
  get 'selects/index'
  root 'pages#help'
  resources :notes do
    resources :notecomments
  end
  resources :pages do
    resources :tweets
  end
  resources :tweets do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :users do
  member do
   get :following, :followers
  end
  end
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  get 'goods/index'
  post '/goods', to: 'goods#create'
  get 'mores/index'
  post '/mores', to: 'mores#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/more.rb
class More < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :notecomments
  has_many :mores
  has_many :more_users, through: :mores, source: 'user'
  belongs_to :user
end

app/models/notecomment.rb
class Notecomment < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :following, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :goods
  has_many :good_users, through: :goods, source: 'user'
  has_many :comments
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :notecomments

  has_many :mores
  has_many :more_notes, through: :mores, source: 'note'
  has_many :goods
  has_many :good_tweets, through: :goods, source: 'tweet'
  has_many :tweets
  has_many :notes
  # フォロー機能関係のコード
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_secure_password

  mount_uploader :image, ImageUploader

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    if following.ids.include?(other_user.id)
      return true
    end
      return false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end

  def index
    @user = User.all
  end

  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])
  if @user.update(user_params)
    redirect_to @user
  else
    render 'edit'
  end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.following
    render '_show_follow'
  end

  def followers
  @user  = User.find(params[:id])
  @users = @user.followers
  render '_show_follower'
  end

  private def user_params
    params.require(:user).permit(:email, :username, :sex, :image, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(tweet)
    tweet.user_id == current_user.id
  end

  def user_confirmation(objects)
    tweet_id = objects.user_id
    if tweet_id == current_user.id
      return true
    else
      return false
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/mores_helper.rb
module MoresHelper
end

app/helpers/notecomments_helper.rb
module NotecommentsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/serch_helper.rb
module SerchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_show_follow.html.erb
<% @user.following.each do |user| %>
<table>
<tr>
  <td>  <%= user.username %> </td>
  <td><%= link_to '詳細', user_path(user) %></td>
</tr>

</table>
<% end %>

app/views/users/_show_follower.html.erb
<div class="container">
  <div class"row">
    <div class"col-md-6 col-md-offset-3">
      <% @user.followers.each do |user| %>
        <table>
          <tr>
            <td>  <%= user.username %> </td>
            <td>  <%= link_to '詳細', user_path(user) %></td>
          </tr>
    </div>
        </table>
      <% end %>
  </div>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="register-photo">
    <div class="form-container">
    <h1 class="text-center projectname">Welcome to pechakucha</h1>
    <a href="/" class="btn btn-sm center-block"><p class="text-center">What's pechakucha?</p><i class="glyphicon glyphicon-plus"></i></a>
        <div class="form1">
            <h2 class="text-center"><strong>Edit</strong> <%=current_user.username%>'s account infomation.</h2>
            <%= form_for @user,url: user_path(current_user), method: :patch, :html => {:class => "form-group"} do |f| %>
            <div class="form-group"><%= f.label :email, class: 'text-white' %><%= f.text_field :email, class: 'form-control' %></div>
            <div class="form-group"><%= f.label :username, class: 'text-white' %><%= f.text_field :username, class: 'form-control' %></div>
            <div class="form-group"><%= f.label :sex, class: 'text-white' %><%= f.text_field :sex, class: 'form-control' %></div>
            <div class="form-group"><%= f.label :image, class: 'text-white' %><%= f.file_field :image, class: 'form-control'%></div>
            <div class="form-group"><%= f.label :description, class: 'text-white' %><%= f.text_area :description, class: 'form-control'%></div>
            <div class="form-group"><%= f.submit "update", class: 'btn-block btn-white' %></div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="team-boxed">
    <div class="container">
        <div class="intro">
            <h1 class="text-center title">User list</h1>
            <h2 class="text-center subtitle">Here you can see all the users who created the account.</h2>
        </div>
        <div class="row people">
          <%@user.each do |user|%>
            <div class="col-md-4 item">
                <div class="box">
                    <h3 class="name text-center username"><%=image_tag user.image.url, class: 'rounded-circle'%>　<%=user.username%></h3>
                    <p class="title text-center"><%=user.sex%></p>
                    <p class="description text-center"><%=user.description%></p>
                    <div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
                </div>
            </div>
          <%end%>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="user-show">
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center title">
      <h1 class="hello">hello <%=current_user.username%> !</h1>
      <h2 class="sub-text">this is your profile page</h2>
    </div>
  </div>
  <div class="row">
    <% if current_user.image.url == nil%>
      <div class="col-md-2"></div>
      <div class="col-md-8 text-center item">
      

          <tr>
            <td><p>self introduction</p></td>
            <td><section class="stats">
            <%= render 'stats' %>
            </td>
            <td><%=link_to 'edit', edit_user_path(current_user) %></td>
          </tr>
      </div>
      <div class="col-md-2"></div>
    <% else %>
      <div class="col-md-2"></div>
      <div class="col-md-8 text-center item">
        <%= image_tag current_user.image.url, class: 'rounded-circle', :size =>'180x180' %>

          <tr>
            <td><p>self introduction</p></td>
            <td><section class="stats">
            <%= render 'stats' %>
            </td>
            <td><%=link_to 'edit', edit_user_path(current_user) %></td>
          </tr>
      </div>
      <div class="col-md-2"></div>
    <% end %>
  </div>
</div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>