config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show, :edit, :update]
  get 'serch/index'
  get 'selects/index'
  root 'pages#help'
  resources :notes do
    resources :notecomments
  end
  resources :pages do
    resources :tweets
  end
  resources :tweets do
    resources :comments
  end
  resources :relationships, only: [:create, :destroy]
  resources :users do
  member do
   get :following, :followers
  end
  end
  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  get 'goods/index'
  post '/goods', to: 'goods#create'
  get 'mores/index'
  post '/mores', to: 'mores#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/more.rb
class More < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :notecomments
  has_many :mores
  has_many :more_users, through: :mores, source: 'user'
  belongs_to :user
end

app/models/notecomment.rb
class Notecomment < ApplicationRecord
  belongs_to :note
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
   belongs_to :follower, class_name: "User"
   belongs_to :following, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :goods
  has_many :good_users, through: :goods, source: 'user'
  has_many :comments
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :notecomments

  has_many :mores
  has_many :more_notes, through: :mores, source: 'note'
  has_many :goods
  has_many :good_tweets, through: :goods, source: 'tweet'
  has_many :tweets
  has_many :notes
  # フォロー機能関係のコード
  has_many :active_relationships,class_name:  "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships,class_name:  "Relationship", foreign_key: "following_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :following
  has_many :followers, through: :passive_relationships, source: :follower

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, on: :create
  validates :password_confirmation, presence: true, on: :create

  has_secure_password

  mount_uploader :image, ImageUploader

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(following_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(following_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    if following.ids.include?(other_user.id)
      return true
    end
      return false
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/mores_helper.rb
module MoresHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/helpers/serch_helper.rb
module SerchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pechakucha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Wendy+One" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif|Wendy+One" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
  <div class="container">
    <%= link_to root_path do %>
      <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li>
          <%= link_to users_path do %>
            <%= image_tag "icons/userlist.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to user_path(@current_user) do %>
            <%= image_tag "icons/profile.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to goods_index_path do %>
            <%= image_tag "icons/good.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to notes_path do %>
            <%= image_tag "icons/note.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to tweets_path do %>
            <%= image_tag "icons/tweet.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to logout_path, method: :delete do %>
            <%= image_tag "icons/logout.png" %>
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to pages_path do %>
            <%= image_tag "icons/register.png" %>
          <% end %>
        </li>
        <li>
          <%= link_to login_path do %>
            <%= image_tag "icons/login.png" %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/help.html.erb
<div class="features-boxed">
    <div class="container">
        <div class="row">
            <div class="intro">
                <h2 class="text-center">pechakuchaってなに？</h2>
                <h4 class="text-center">ペチャクチャは皆が自由にスポーツについて話すことができ、皆が自由にスポーツノートを書くことができるアプリケーションです。</h4>
            </div>
        </div>
        <div class="row justify-content-center features">
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-map-marker icon"></i>
                    <h3 class="name">Write your thoughts on the sports note more and more!</h3>
                    <p class="description">どんどん思ったことをスポーツノートに書いて！</p><a href="/notes/new" class="learn-more">Learn more »</a></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-clock-o icon"></i>
                    <h3 class="name">Please tweet! Like a twitter</h3>
                    <p class="description">どんどん思ったことを呟いて！Twitterみたいに！</p><a href="/tweets/new" class="learn-more">Learn more »</a></div>
            </div>
            <div class="col-sm-6 col-md-5 col-lg-4 item">
                <div class="box"><i class="fa fa-list-alt icon"></i>
                    <h3 class="name">Let's make friends with many people!</h3>
                    <p class="description">どんどんフォローして多くの人と友達になろう！</p><a href="/pages#index" class="learn-more">Learn more »</a></div>
            </div>
        </div>
        <div class="row self-produce">
            <div class="col-md-12 text-center self-produce">
                <h2 class="self-introduction">・SELF　INTRODUCTION・</h2>
            </div>
        </div>
        <div class="row row4">
            <div class="col-md-4 self-introduction-box">
                <div class="box">
                    <h3 class="text-center font">Basic information</h3>
                    <h4 class="text-center font"> ・Developer・</h4><p class="text-center my-information">GAKU</p>
                    <h4 class="text-center font"> ・Age・</h4><p class="text-center my-information">21</p>
                    <h4 class="text-center font"> ・Job category・</h4><p class="text-center my-information">student</p>
                    <h4 class="text-center font"> ・Used programming language・</h4><p class="text-center my-information">html　css　ruby　javascript</p>
                    <h4 class="text-center font"> ・Used Framework・</h4><p class="text-center my-information">bootstrap　JQuery　Rubyonrails </p>
                    <h4 class="text-center font"> ・Production period・</h4><p class="text-center my-information">about　1month</p>
                    <h4 class="text-center font"> ・Learning period・</h4><p class="text-center my-information">3month</p>
                </div>
            </div>
            <div class="col-md-8 self-introduction-box">
                <div class="box">
                    <h3 class="text-center font">Other　information </h3>
                    <h4 class="text-center font">&#x1f447;My SNS acount&#x1f447;</h4>
                    <h5 class="text-center font">please　follow　me!!! </h5>
                        <div class="social text-center">
                            <a href="https://twitter.com/GeminiTennis?lang=ja"><%= image_tag 'icons/twitter.png', class: 'topic-index-icon' %></a>
                            <a href="https://www.instagram.com/tennis_0521/"><%= image_tag 'icons/instagram.png', class: 'topic-index-icon' %></a>
                            <p class="text-center">自分の初めて作ったWebアプリケーションです。全然立派なものではありませんが３ヶ月間没頭しました。今後は、２作目のWebアプリケーションの作成に取り掛かろうと思います。
                            何か質問などがあれば上記のアカウントまで連絡ください！！！ </p>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/index.html.erb
<div class="register-photo">
    <div class="form-container">
      <h1 class="text-center projectname">Welcome to pechakucha</h1>
      <p class="text-center">What's pechakucha?</p>
        <div class="form1">
            <h2 class="text-center"><strong>Create</strong> an account.</h2>
            <%= form_for :@user,url: pages_path do |f| %>
            <div class="form-group"><%= f.label :email, class: 'text-white' %><%= f.text_field :email, class: 'form-control' %></div>
            <div class="form-group"><%= f.label :username, class: 'text-white' %><%= f.text_field :username, class: 'form-control' %></div>
            <div class="form-group"><%= f.label :password, class: 'text-white' %><%= f.text_field :password, class: 'form-control' %></div>
            <div class="form-group"><%= f.label :password_confirmation, class: 'text-white' %><%= f.password_field :password_confirmation, class: 'form-control' %></div>
            <div class="form-group"><%= f.submit "create", class: 'btn-block btn-white' %></div><a href="/login" class="already">You already have an account? Login here.</a>
            <% end %>
        </div>
    </div>
</div>